service: express-sls-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: eu-central-1
  memorySize: 1024
  environment: 
    NODE_ENV: 'production'

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline